### ISSUE TITLE
Docker build gets stuck web running: 'RUN npx webpack' — doesn't move to next step in dockerfile

### ISSUE THREAD

**Issue by adsy** [Apress/modern-full-stack-development#21]
I am trying to build my project into a container for Docker with the following dockerfile:

```
FROM node:10
WORKDIR /usr/app/battlejong
COPY client ./client
COPY BattleJongServer ./BattleJongServer
WORKDIR /usr/app/battlejong/client
RUN npm install
RUN npx webpack
WORKDIR /usr/app/battlejong/BattleJongServer
RUN npm install
RUN npx tsc
EXPOSE 80
CMD ["node","./dist/main.js"]
```

The docker build runs and completes the webpack step but does not continue onto the next step of changing the directory.

Here is the output here:

```
Step 1/12 : FROM node:10
 ---> 1e318dc8ae6f
Step 2/12 : WORKDIR /usr/app/battlejong
 ---> Using cache
 ---> c004d781a932
Step 3/12 : COPY client ./client
 ---> 955204bda599
Step 4/12 : COPY BattleJongServer ./BattleJongServer
 ---> 6c692d4c4bad
Step 5/12 : WORKDIR /usr/app/battlejong/client
 ---> Running in 662e29660e6c
Removing intermediate container 662e29660e6c
 ---> 3ce3c61bf582
Step 6/12 : RUN npm install
 ---> Running in 808724a44e9b
npm WARN client@1.0.0 No description
npm WARN client@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 678 packages from 430 contributors and audited 684 packages in 12.37s

29 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Removing intermediate container 808724a44e9b
 ---> 0dc996f51895
Step 7/12 : RUN npx webpack
 ---> Running in bd591d5fc8f8

webpack is watching the files…

ℹ ｢atl｣: Using typescript@4.0.2 from typescript
ℹ ｢atl｣: Using tsconfig.json from /usr/app/battlejong/client/tsconfig.json
ℹ ｢atl｣: Checking started in a separate process...
ℹ ｢atl｣: Time: 1712ms
Hash: 99e556545c8a1a30d23c
Version: webpack 4.44.1
Time: 9256ms
Built at: 09/15/2020 12:10:54 AM
       Asset       Size  Chunks                          Chunk Names
./index.html  241 bytes          [emitted]               
     main.js    276 KiB       0  [emitted]        [big]  main
 main.js.map    508 KiB       0  [emitted] [dev]         main
Entrypoint main [big] = main.js main.js.map
 [4] ./src/code/main.tsx 550 bytes {0} [built]
 [7] ./src/css/main.css 524 bytes {0} [built]
 [8] ./node_modules/css-loader/dist/cjs.js!./src/css/main.css 3.39 KiB {0} [built]
[17] ./src/img/tile101.png 5.59 KiB {0} [built]
[18] ./src/img/tile102.png 3.15 KiB {0} [built]
[19] ./src/img/tile103.png 2.58 KiB {0} [built]
[20] ./src/img/tile104.png 1.14 KiB {0} [built]
[21] ./src/img/tile105.png 2.39 KiB {0} [built]
[22] ./src/img/tile106.png 2.1 KiB {0} [built]
[23] ./src/img/tile107.png 3.49 KiB {0} [built]
[24] ./src/img/tile108.png 2.53 KiB {0} [built]
[25] ./src/img/tile109.png 2.53 KiB {0} [built]
[26] ./src/img/tile110.png 2.29 KiB {0} [built]
[27] ./src/img/tile111.png 1.58 KiB {0} [built]
[59] ./src/code/state.tsx 12.9 KiB {0} [built]
    + 46 hidden modules

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
Child HtmlWebpackCompiler:
     1 asset
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 287 bytes {0} [built]
```

And then the build doesn't proceed from here onto line/step 8 in the dockerfile and will sit here until I force stop the build.

Any help would be appreciated :)

**Comment by fzammetti** [comment]
Hi,

If I'm not mistaken, you're running into the problem detailed on page (I think) 364.  Here's the relevant part:

> Now, if you do this, you will hit a problem when Docker gets to the RUN npm webpack –mode production line: it will hang, never completing the image. The reason is straightforward: remember that we configured Webpack to monitor our files and automatically rebuild when they change? Well, that’s exactly what it’s going to do as the image is being built, so it will never complete. To fix that, you need to go into the webpack.config.js file and set watch to false. After that, the build should be successful and everything else should work as expected.

The giveaway I think is in the output your show here where it says "webpack is watching the files…"  See if that does the trick.

**Comment by adsy** [comment]
@fzammetti Hi thank you for that fast response, that did that trick and now the load builds completely. However when I start the docker instance it instantly turns off and the docker logs show this error:

```
internal/modules/cjs/loader.js:638

throw err;

^


Error: Cannot find module '/usr/app/battlejong/BattleJongServer/dist/main.js'

at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)

at Function.Module._load (internal/modules/cjs/loader.js:562:25)

at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

at startup (internal/bootstrap/node.js:283:19)

at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

Im not sure why its trying to grab dist/main from the server as the webpack config is set for the client side?

**Comment by fzammetti** [comment]
Hmm... you're correct that Webpack is only handling the client... when you compile the server, you should wind up with main.js in the dist folder, that's why it's looking for it.  Is it possible you didn't compile the server?  That would explain the error.  The step in the Dockerfile that's copying the server would effectively be copying an empty directory, or at least one not having the necessary file, so you wouldn't see an error on that step, but at runtime, you'd get the error you're seeing.

**Comment by fzammetti** [comment]
And, you know what?  I just looked at the chapter on the server and I don't see anywhere that I say to compile the server, so that's my fault.

**Comment by adsy** [comment]
Haha makes sense! Can you please provide me the steps for this for Mailbag
and Battlejong and I’ll be able to successfully deploy on docker :)

**Comment by fzammetti** [comment]
Sorry I didn't get back to you sooner, I missed the GitHub reply notification in my overstuffed inbox :(

Anyway, it should be as easy as going into the server source directory and executing **npm install** followed by **npx tsc**.  The install of course installs all the dependencies, which includes TypeScript here.  Using npx is how you execute tools installed locally (read: within the project rather than globally), which includes TypeScript.  After that, you should have the dist directory and the contents you need to deploy the container successfully.

**Comment by fzammetti** [comment]
Hi,

Did this work out for you?
